/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PartB;
import PartA.*;

import java.util.ArrayList;
import java.util.Arrays;

import PartA.Module;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;

public class App {
    public static void main(String[] args) {
        Student s1 = new Student("Bradley Bradley", 21, "25/09/1999", 198323429);
        Student s2 = new Student("Bradley Brown", 21, "11/01/1999", 53373123432);
        Student s3 = new Student("Brown Bradley", 21, "01/01/1999", 1281812421);

        ArrayList<Student> students = new ArrayList<Student>(Arrays.asList(s1, s2, s3));

        String formatter = "yyyy-dd-MM hh:mm:ss";
        Course course1 = new Course(
                "CSIT",
                DateTime.parse("2021-01-10 00:00:00", DateTimeFormat.forPattern(formatter)),
                DateTime.parse("2022-01-10 00:00:00", DateTimeFormat.forPattern(formatter)));
        Course course2 = new Course(
                "ARTS",
                DateTime.parse("2021-01-10 00:00:00", DateTimeFormat.forPattern(formatter)),
                DateTime.parse("2022-01-10 00:00:00", DateTimeFormat.forPattern(formatter)));

        PartA.Module module1 = new PartA.Module("Software Engineering", "CT417");
        PartA.Module module2 = new PartA.Module("Machine Learning", "CT4101");

        // Add students to modules.
        module1.setStudents(new ArrayList<Student>(Arrays.asList(s1, s2)));
        module2.setStudents(new ArrayList<Student>(Arrays.asList(s1, s2, s3)));

        s1.setModules(new ArrayList<Module>(Arrays.asList(module1, module2, module3)));
        s2.setModules(new ArrayList<Module>(Arrays.asList(module1, module2)));
        s3.setModules(new ArrayList<Module>(Arrays.asList(module2)));


        // Add modules to courses.
        course1.setModules(new ArrayList<PartA.Module>(Arrays.asList(module1, module2, module3)));
        
        course2.setModules(new ArrayList<PartA.Module>(Arrays.asList(module3, module4)));

        // Add students to courses.
        course1.setStudents(new ArrayList<Student>(Arrays.asList(s1, s2, s3)));
        
        course2.setStudents(new ArrayList<Student>(Arrays.asList(s4, s5)));
        
        s1.setCourses(new ArrayList<Course>(Arrays.asList(course1)));
        
        s2.setCourses(new ArrayList<Course>(Arrays.asList(course1)));
     
        s3.setCourses(new ArrayList<Course>(Arrays.asList(course1)));


        System.out.println(course1);
        System.out.println(course2);

        for(Student student : students) {
            System.out.println(student);
        }
    }
}
